### ISSUE TITLE
Add SchemaHero CRD

### ISSUE THREAD

**Issue by marccampbell** [crdsdev/doc#66]
Can we get https://github.com/schemahero/schemahero added to the site? I'd be happy to make a PR if it's preferred.

**Comment by hasheddan** [comment]
@marccampbell we can definitely get this added :)

**Comment by hasheddan** [comment]
@marccampbell you can now find the `schemahero` CRDs at https://doc.crds.dev/github.com/schemahero/schemahero :)

You will notice that each CRD is listed twice due to the fact that there are `v1` and `v1beta1` versions of each. We have discussed adding support for a config file in repos to restrict paths that are parsed (https://github.com/crdsdev/doc/issues/64), is that something you would be interested in adding in the `schemahero` repo?
