### ISSUE TITLE
Detect all CRDs under a path

### ISSUE THREAD

**Issue by negz** [crdsdev/doc#9]
The CRD doc experience feels similar to https://godoc.org. One feature I appreciate about https://godoc.org is that I can browse to either a repository root like https://godoc.org/github.com/crossplaneio/crossplane-runtime or a path within a repository like https://godoc.org/github.com/crossplaneio/crossplane-runtime/pkg/reconciler and I'll be shown all the packages under that path. It would be very helpful if CRD doc had similar functionality - i.e. if I browsed to https://doc.crds.dev/github.com/crossplaneio I would see all the known CRDs of the Crossplane project.

**Comment by hasheddan** [comment]
@negz this is an awesome and necessary feature! I notice that you mentioned that you would like to be able to navigate to the **org** path and be able to see all CRDs. Godoc does not allow for this as it mandates that you must be at least at the **repo** path. Even parsing at the repo level is a little more difficult for us because CRDs are not identifiable by file type. We can narrow down to `yaml` / `yml`, but then we have to inspect the actual content of the file to determine if it is in fact a CRD.

All of that being said, do you think being able to get a list at the **repo** path instead of the **org** path would be suitable?

**Comment by hasheddan** [comment]
Ref: #10

**Comment by negz** [comment]
> All of that being said, do you think being able to get a list at the repo path instead of the org path would be suitable?

Yes, repo is fine - I linked to the org by accident.

**Comment by negz** [comment]
I believe that as of #10 you're finding all YAML files within a repo (even if they're not CRDs). It would be handy to check the files for the CRD apiVersion and group to further filter them down.

**Comment by hasheddan** [comment]
@negz we actually are already filtering based on `kind: CustomResourceDefinition` being present in the YAML file https://github.com/crdsdev/doc/blob/efe506e75402a68426356a4f7d205fa98355ec7d/main.go#L88

**Comment by hasheddan** [comment]
Closing this as fixed by #10. Improved parsing will likely still be needed, but may be solved as part of the work around #13
